### PR TITLE
Updated Dependencies & made recursive in maven style for easier usage.

### PR DESCRIPTION
**Pull request by hazendaz**
1) Implemented Maven 3.1.x
2) Updated third party dependencies to latest.  Did not update
htmlcompressor to 1.5.3 as it is currently not available in maven
central.  However, this version as well as prior work with 1.5.3 without
issue.
3) Updated property settings annotation in code based on maven 3.1.x
changes
4) Minor cleanup (removing unused imports deleting duplicate blank
lines)
5) Made compression recursive so additional properties are not required
to get this working.  This matches how yui compressor maven task works
as well as ant based versions of yui compressor and htmlcompressor.
This fixes one noted issue on github.  Items are picked up from
src/main/resource and placed in proper place under target/classes.
6) Updated readme to match recursive nature of project now.

### CODE REVIEW

**Comment by hazendaz** [comment]
Any status on this PR request?

**Comment by hazendaz** [comment]
Well it's been over a year and another week since mentioning this.  Well I can now just release this under my own sonatype account.  I'd like to see this move forwards so I can utilize easily the changes I've made.  I can keep this PR in place but if I go that direction it will change to match my coordinates.  Please advice if you have time.  Thanks.

**Comment by alextunyk** [comment]
Jeremy,

Thanks for your contribution.

I've accepted your push request however I have few notes.
  1. Your changes are not backward compatible and breaks the concepts behind htmlcompressor which have an option --type <html|xml>
     The option allows a user to limit processing on the given type files only.
     I suggest to add another maven goal named 'all' which processes all of the files (autodetects from file extension): the same behaviour like htmlcompressor for the case when --type is omitted.
  2. As you might noticed tests are not accomplished and there is a demo attached (https://github.com/alextunyk/htmlcompressor-maven-plugin/downloads).
        Please download that demo project, run it against version 1.3 then run against 1.4-SNAPSHOT
        The diff will show the regression you've introduced with your changes.

I'm going to fix it like I've described above and push it to maven central as 1.4

Please let me know if you have any comments.

**Comment by hazendaz** [comment]
Thanks for the detailed information.  I'll check all this out...

--- Original Message ---

**Comment by hazendaz** [comment]
It will be a couple of days before I get a change to really look into what my changes caused.  I will get to this even if you do end up fixing before then I want to understand where I went wrong.  Thanks.

**Comment by hazendaz** [comment]
Not sure this actually broke any backwards compatibility.  Execution phase can determine what type to apply with so it doesn't need to simply ignore all.  We have successfully been running separate execution phases for a very long time and only what we require be picked up are.  I will take a look at this again though as I've ported htmlcompressor itself over to github and will ultimately repoint this plugin to my version as original is essentially all but officially flagged EOL.

**Pull request merged**
